<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epo2" nsURI="http:///epo2.ecore" nsPrefix="epo2">
  <eClassifiers xsi:type="ecore:EDataType" name="SKU" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderStatus">
    <eLiterals name="Pending"/>
    <eLiterals name="BackOrder" value="1"/>
    <eLiterals name="Complete" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" ordered="false"
        upperBound="-1" eType="#//PurchaseOrder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pendingOrders" ordered="false"
        upperBound="-1" eType="#//PurchaseOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shippedOrders" ordered="false"
        upperBound="-1" eType="#//PurchaseOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" ordered="false"
        upperBound="-1" eType="#//Customer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PurchaseOrder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false"
        lowerBound="1" eType="#//OrderStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAmount" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" ordered="false"
        lowerBound="1" eType="#//Customer" eOpposite="#//Customer/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousOrder" ordered="false"
        eType="#//PurchaseOrder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" ordered="false"
        upperBound="-1" eType="#//Item" containment="true" eOpposite="#//Item/order"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="billTo" ordered="false"
        lowerBound="1" eType="#//Address" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shipTo" ordered="false"
        lowerBound="1" eType="#//Address" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerID" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" ordered="false"
        upperBound="-1" eType="#//PurchaseOrder" eOpposite="#//PurchaseOrder/customer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usPrice" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shipDate" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partNum" ordered="false"
        lowerBound="1" eType="#//SKU"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" ordered="false"
        lowerBound="1" eType="#//PurchaseOrder" eOpposite="#//PurchaseOrder/items"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USAddress" eSuperTypes="#//Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalAddress" eSuperTypes="#//Address #//GlobalLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="countryCode" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
